title: markdown-project-template
description: Template for a DH Project Using MarkDown and GitHub Pages
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CHANGELOG.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - LICENSE
  - PULL_REQUEST_TEMPLATE.md
  - README.md
theme: jekyll-theme-cayman
source: ./pages
collections_dir: ./pages
includes_dir: _includes
